repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
    
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
    
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.0.9
    hooks:
    -   id: isort
    
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.3
    hooks:
    -   id: pylint
        args:
        - --max-line-length=130
        - --ignore-imports=yes
        - --disable=C0114,E0401,R0912,R0914,R1702,R0915,R0801,C0330
        - --good-names=i,j
        - --ignore-patterns=conf.py
